Support bio marker mapping of qualifier mode to Carebox API' bio Mark…
mcode/clinical-trial-matching-service-carebox pull request #2
Opened 2023-02-23 09:13 UTC by einav-cb

…er status (positive/negative)

Pull requests into the clinical-trial-matching-service-template require the following. Submitter should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] Make sure test coverage didn’t decrease. If you are allowing the test coverage to drop, leave an explanation as to why:
- [ ]	Does an update need to be made to the documentation with these changes?
- [ ]	Does an update need to be made to the service wrappers as well?
- [ ]	Does an update need to be made to the service library?
- [ ] Was the new feature tested by unit tests?
- [ ] Was the new feature tested by a manual, end-to-end test?

2023-02-23 21:32 UTC, ChristineDuong approved these changes

2023-02-28 19:54 UTC, zlister commented on src/mappers.ts
> +                                    valueId: geneDetails.code,
remove extra comma

2023-02-28 19:56 UTC, zlister requested changes

2023-02-28 19:56 UTC, zlister commented on src/mappers.ts
> +                                    valueId: geneDetails.code,
Remove comma

2023-03-01 14:43 UTC, zlister approved these changes

2023-03-01 14:43 UTC, merged